# Generated by Django 4.2.15 on 2024-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_field_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_2',
        ),
    ]
